/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controlador.ControladorCliente;
import controlador.ControladorProduto;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.Cliente;
import utils.Produto;

/**
 *
 * @author Igor
 */
public class PainelGerenciarProdutos extends javax.swing.JPanel {

    ArrayList<Produto> produtos = null;
    ControladorProduto controladorProduto = new ControladorProduto();
    DefaultTableModel modelUsuarios;
    String codigoSelecionado = "";
    boolean grupoSelecionado = false;
    /**
     * Creates new form PainelGerenciarClientes
     */
    public PainelGerenciarProdutos() {
        initComponents();
        modelUsuarios = (DefaultTableModel) tabelaProdutos.getModel();

        this.campoBuscaCodigo.setEnabled(false);
        this.campoBuscaNome.setEnabled(false);
        this.abasProduto.setEnabledAt(0, true);
        this.abasProduto.setEnabledAt(1, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraCliente = new javax.swing.JToolBar();
        adicionarProduto = new javax.swing.JButton();
        editarProduto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        abasProduto = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoCodigoAddProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoNomeAddProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoQuantidadeAddProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoPrecoCustoAddProduto = new javax.swing.JTextField();
        botaoConfirmarProduto = new javax.swing.JButton();
        cancelarBotao = new javax.swing.JButton();
        campoPrecoPorUnidadeAddProduto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        radioGrupoBF = new javax.swing.JRadioButton();
        radioGrupoVS = new javax.swing.JRadioButton();
        radioGrupoEP = new javax.swing.JRadioButton();
        radioGrupoMT = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoBuscaCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoBuscaNome = new javax.swing.JTextField();
        buscarProduto = new javax.swing.JButton();
        atualizaCliente = new javax.swing.JButton();
        novoCodigo = new javax.swing.JTextField();
        novoNome = new javax.swing.JTextField();
        novoPrecoUnidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        checkCPF = new javax.swing.JCheckBox();
        checkNome = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        selecionaProduto = new javax.swing.JButton();
        removerCliente = new javax.swing.JButton();
        novaQuantidade = new javax.swing.JTextField();
        novoTipo = new javax.swing.JTextField();

        barraCliente.setOrientation(javax.swing.SwingConstants.VERTICAL);
        barraCliente.setRollover(true);

        adicionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionarProduto.png"))); // NOI18N
        adicionarProduto.setText("Adicionar");
        adicionarProduto.setFocusable(false);
        adicionarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adicionarProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        adicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarProdutoActionPerformed(evt);
            }
        });
        barraCliente.add(adicionarProduto);

        editarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editClient.png"))); // NOI18N
        editarProduto.setText("Editar");
        editarProduto.setFocusable(false);
        editarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProdutoActionPerformed(evt);
            }
        });
        barraCliente.add(editarProduto);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Adição de Produtos");

        jLabel2.setText("Código do produto:");

        jLabel3.setText("Nome do produto:");

        jLabel4.setText("Quantidade do produto:");

        jLabel5.setText("Preço de custo:");

        botaoConfirmarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/select.png"))); // NOI18N
        botaoConfirmarProduto.setText("Confirmar");
        botaoConfirmarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarProdutoActionPerformed(evt);
            }
        });

        cancelarBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        cancelarBotao.setText("Cancelar");
        cancelarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotaoActionPerformed(evt);
            }
        });

        jLabel10.setText("Preço de venda (unidade):");

        radioGrupoBF.setText("BF");
        radioGrupoBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGrupoBFActionPerformed(evt);
            }
        });

        radioGrupoVS.setText("VS");
        radioGrupoVS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGrupoVSActionPerformed(evt);
            }
        });

        radioGrupoEP.setText("EP");
        radioGrupoEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGrupoEPActionPerformed(evt);
            }
        });

        radioGrupoMT.setText("MT");
        radioGrupoMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGrupoMTActionPerformed(evt);
            }
        });

        jLabel11.setText("Grupo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(campoNomeAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoCodigoAddProduto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                            .addComponent(campoQuantidadeAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoPrecoPorUnidadeAddProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addComponent(campoPrecoCustoAddProduto, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(radioGrupoBF)
                                .addGap(18, 18, 18)
                                .addComponent(radioGrupoVS)
                                .addGap(18, 18, 18)
                                .addComponent(radioGrupoEP)
                                .addGap(10, 10, 10)
                                .addComponent(radioGrupoMT))
                            .addComponent(jLabel11)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(botaoConfirmarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarBotao)))
                .addContainerGap(414, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCodigoAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNomeAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoQuantidadeAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPrecoCustoAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPrecoPorUnidadeAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioGrupoBF)
                    .addComponent(radioGrupoVS)
                    .addComponent(radioGrupoEP)
                    .addComponent(radioGrupoMT))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConfirmarProduto)
                    .addComponent(cancelarBotao))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        abasProduto.addTab("Adicionar", jPanel2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Edição de Produtos");

        jLabel7.setText("Busque o produto por código");

        jLabel8.setText("Busque o produto pelo nome");

        buscarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        buscarProduto.setText("Buscar");
        buscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProdutoActionPerformed(evt);
            }
        });

        atualizaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit.png"))); // NOI18N
        atualizaCliente.setText("Editar");
        atualizaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaClienteActionPerformed(evt);
            }
        });

        jLabel9.setText("Digite os novos campos:");

        checkCPF.setText("Busque pelo código");
        checkCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCPFActionPerformed(evt);
            }
        });

        checkNome.setText("Busque pelo nome");
        checkNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNomeActionPerformed(evt);
            }
        });

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Preço", "Quantidade", "Grupo"
            }
        ));
        jScrollPane1.setViewportView(tabelaProdutos);

        selecionaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/select.png"))); // NOI18N
        selecionaProduto.setText("Selecionar");
        selecionaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionaProdutoActionPerformed(evt);
            }
        });

        removerCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove.png"))); // NOI18N
        removerCliente.setText("Remover");
        removerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(novoPrecoUnidade)
                                    .addComponent(novoNome)
                                    .addComponent(novoCodigo)
                                    .addComponent(novaQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                                    .addComponent(novoTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(selecionaProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(atualizaCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removerCliente)))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(campoBuscaCodigo)
                            .addComponent(campoBuscaNome, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkCPF)
                            .addComponent(checkNome))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(buscarProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(154, 154, 154))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBuscaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkCPF))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkNome))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(novoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(novoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(novoPrecoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(novaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(novoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(selecionaProduto)
                                    .addComponent(atualizaCliente)
                                    .addComponent(removerCliente)))))
                    .addComponent(buscarProduto))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        abasProduto.addTab("Editar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abasProduto))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(abasProduto)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarProdutoActionPerformed
        abasProduto.setSelectedIndex(0);
        this.abasProduto.setEnabledAt(0, true);
        this.abasProduto.setEnabledAt(1, false);
    }//GEN-LAST:event_adicionarProdutoActionPerformed

    private void editarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProdutoActionPerformed
        abasProduto.setSelectedIndex(1);
        this.abasProduto.setEnabledAt(0, false);
        this.abasProduto.setEnabledAt(1, true);
    }//GEN-LAST:event_editarProdutoActionPerformed

    private void cancelarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotaoActionPerformed
        
        this.campoCodigoAddProduto.setText("");
        this.campoNomeAddProduto.setText("");
        this.campoPrecoCustoAddProduto.setText("");
        this.campoPrecoPorUnidadeAddProduto.setText("");
        this.campoQuantidadeAddProduto.setText("");
        
        this.radioGrupoBF.setSelected(false);
        this.radioGrupoVS.setSelected(false);
        this.radioGrupoMT.setSelected(false);
        this.radioGrupoEP.setSelected(false);
        
        grupoSelecionado = false;
    }//GEN-LAST:event_cancelarBotaoActionPerformed

    private void botaoConfirmarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarProdutoActionPerformed
        int tipo = -1;
        
        if (radioGrupoBF.isSelected())
            tipo = 0;
        else if (radioGrupoVS.isSelected())
            tipo = 1;
        else if (radioGrupoEP.isSelected())
            tipo = 2;
        else if (radioGrupoMT.isSelected())
            tipo = 3;
        
        if (!campoCodigoAddProduto.getText().equals("") && !campoNomeAddProduto.equals("") && !campoPrecoCustoAddProduto.equals("") && !campoPrecoPorUnidadeAddProduto.equals("")  && !campoQuantidadeAddProduto.equals("") && grupoSelecionado) {
            controladorProduto.insereProdutos(campoCodigoAddProduto.getText(), campoNomeAddProduto.getText(), campoPrecoPorUnidadeAddProduto.getText(), campoPrecoCustoAddProduto.getText(), Integer.parseInt(campoQuantidadeAddProduto.getText()),tipo);
            JOptionPane.showMessageDialog(null, "Produto adicionado com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Todos os campos precisam ser preenchidos");
        }

        this.campoCodigoAddProduto.setText("");
        this.campoNomeAddProduto.setText("");
        this.campoPrecoCustoAddProduto.setText("");
        this.campoPrecoPorUnidadeAddProduto.setText("");
        this.campoQuantidadeAddProduto.setText("");
        
        this.radioGrupoBF.setSelected(false);
        this.radioGrupoVS.setSelected(false);
        this.radioGrupoMT.setSelected(false);
        this.radioGrupoEP.setSelected(false);
        
    }//GEN-LAST:event_botaoConfirmarProdutoActionPerformed

    private void buscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProdutoActionPerformed


        if (campoBuscaNome.getText() != null && !campoBuscaNome.getText().equals("") && campoBuscaNome.isEnabled()) {
            produtos = controladorProduto.buscaProdutosPorNome(campoBuscaNome.getText());
        } else if (campoBuscaCodigo.getText() != null && !campoBuscaCodigo.getText().equals("") && campoBuscaCodigo.isEnabled()) {
            produtos = controladorProduto.buscaClientesPorCodigo(campoBuscaCodigo.getText());
        }

        modelUsuarios.setNumRows(0);


        for (int i = 0; i < produtos.size(); i++) {
            Vector vec = new Vector();
            vec.add(0, produtos.get(i).getCodigo());
            vec.add(1, produtos.get(i).getNome());
            vec.add(2, produtos.get(i).getPrecoPorUnidade());
            vec.add(3, produtos.get(i).getQuantidadeEstoque());
            vec.add(4, produtos.get(i).getTipoProduto());
            modelUsuarios.addRow(vec);
        }

        this.repaint();
    }//GEN-LAST:event_buscarProdutoActionPerformed

    private void atualizaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaClienteActionPerformed
        novoTipo.setText(novoTipo.getText().toUpperCase());
        if (novoTipo.getText().equals("EP") || novoTipo.getText().equals("MT") || novoTipo.getText().equals("VS") || novoTipo.getText().equals("BF")) {
        
        if (!novoCodigo.getText().equals("") && !novoNome.getText().equals("") && !novoPrecoUnidade.getText().equals("") && !novoTipo.equals("") && !novaQuantidade.getText().equals("") && tabelaProdutos.getSelectedRow()!= -1 && !codigoSelecionado.equals("")) {
            controladorProduto.atualizaProduto(novoCodigo.getText(), novoNome.getText(), novoPrecoUnidade.getText(), Integer.parseInt(novaQuantidade.getText()), novoTipo.getText(), codigoSelecionado);
            JOptionPane.showMessageDialog(this, "Produto atualizado com sucesso", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Campos precisam ser preenchidos", null, JOptionPane.OK_OPTION);

        }
        } else {
             JOptionPane.showMessageDialog(this, "Grupo de produto inexistente", null, JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_atualizaClienteActionPerformed

    private void checkCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCPFActionPerformed
        if (checkCPF.isSelected()) {
            campoBuscaCodigo.setEnabled(true);
            checkNome.setSelected(false);
            campoBuscaNome.setEnabled(false);
        } else {
            campoBuscaCodigo.setEnabled(false);
        }
    }//GEN-LAST:event_checkCPFActionPerformed

    private void checkNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNomeActionPerformed
        if (checkNome.isSelected()) {
            campoBuscaNome.setEnabled(true);
            campoBuscaCodigo.setEnabled(false);
            checkCPF.setSelected(false);
        } else {
            campoBuscaNome.setEnabled(false);
        }
    }//GEN-LAST:event_checkNomeActionPerformed

    private void selecionaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionaProdutoActionPerformed
        try {
            int selecionado = tabelaProdutos.getSelectedRow();
            Produto produtoSelecionado = produtos.get(selecionado);
            novoCodigo.setText(produtoSelecionado.getCodigo());
            novoNome.setText(produtoSelecionado.getNome());
            novoPrecoUnidade.setText(produtoSelecionado.getPrecoPorUnidade());
            novoTipo.setText(produtoSelecionado.getTipoProduto());
            novaQuantidade.setText(String.valueOf(produtoSelecionado.getQuantidadeEstoque()));
            
            codigoSelecionado = produtoSelecionado.getCodigo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Um produto deve ser selecionado na tabela", null, JOptionPane.OK_OPTION);

        }
    }//GEN-LAST:event_selecionaProdutoActionPerformed

    private void removerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerClienteActionPerformed
        if (!codigoSelecionado.equals("") && codigoSelecionado!=null && tabelaProdutos.getSelectedRow()!=-1) {
            controladorProduto.deletaProdutosPorCodigo(codigoSelecionado);
            JOptionPane.showMessageDialog(this, "Produto removido com sucesso", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Um produto deve ser selecionado na Tabela", null, JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_removerClienteActionPerformed

    private void radioGrupoBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGrupoBFActionPerformed
        this.radioGrupoBF.setSelected(true);
        this.radioGrupoVS.setSelected(false);
        this.radioGrupoMT.setSelected(false);
        this.radioGrupoEP.setSelected(false);
        grupoSelecionado = true;
    }//GEN-LAST:event_radioGrupoBFActionPerformed

    private void radioGrupoVSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGrupoVSActionPerformed
        this.radioGrupoBF.setSelected(false);
        this.radioGrupoVS.setSelected(true);
        this.radioGrupoMT.setSelected(false);
        this.radioGrupoEP.setSelected(false);
        grupoSelecionado = true;
    }//GEN-LAST:event_radioGrupoVSActionPerformed

    private void radioGrupoEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGrupoEPActionPerformed
        this.radioGrupoBF.setSelected(false);
        this.radioGrupoVS.setSelected(false);
        this.radioGrupoMT.setSelected(false);
        this.radioGrupoEP.setSelected(true);
        grupoSelecionado = true;
    }//GEN-LAST:event_radioGrupoEPActionPerformed

    private void radioGrupoMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGrupoMTActionPerformed
        this.radioGrupoBF.setSelected(false);
        this.radioGrupoVS.setSelected(false);
        this.radioGrupoMT.setSelected(true);
        this.radioGrupoEP.setSelected(false);
        grupoSelecionado = true;
    }//GEN-LAST:event_radioGrupoMTActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abasProduto;
    private javax.swing.JButton adicionarProduto;
    private javax.swing.JButton atualizaCliente;
    private javax.swing.JToolBar barraCliente;
    private javax.swing.JButton botaoConfirmarProduto;
    private javax.swing.JButton buscarProduto;
    private javax.swing.JTextField campoBuscaCodigo;
    private javax.swing.JTextField campoBuscaNome;
    private javax.swing.JTextField campoCodigoAddProduto;
    private javax.swing.JTextField campoNomeAddProduto;
    private javax.swing.JTextField campoPrecoCustoAddProduto;
    private javax.swing.JTextField campoPrecoPorUnidadeAddProduto;
    private javax.swing.JTextField campoQuantidadeAddProduto;
    private javax.swing.JButton cancelarBotao;
    private javax.swing.JCheckBox checkCPF;
    private javax.swing.JCheckBox checkNome;
    private javax.swing.JButton editarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField novaQuantidade;
    private javax.swing.JTextField novoCodigo;
    private javax.swing.JTextField novoNome;
    private javax.swing.JTextField novoPrecoUnidade;
    private javax.swing.JTextField novoTipo;
    private javax.swing.JRadioButton radioGrupoBF;
    private javax.swing.JRadioButton radioGrupoEP;
    private javax.swing.JRadioButton radioGrupoMT;
    private javax.swing.JRadioButton radioGrupoVS;
    private javax.swing.JButton removerCliente;
    private javax.swing.JButton selecionaProduto;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
}
