/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Igor
 */
public class PainelGeracaoDeRelatorios extends javax.swing.JPanel {

    /**
     * Creates new form PainelGeracaoDeRelatorios
     */
    public PainelGeracaoDeRelatorios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraCliente = new javax.swing.JToolBar();
        clientesRelatorio = new javax.swing.JButton();
        transacoesRelatorio = new javax.swing.JButton();
        produtosRelatorio = new javax.swing.JButton();
        notasDeVendaRelatório = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        barraCliente.setOrientation(javax.swing.SwingConstants.VERTICAL);
        barraCliente.setRollover(true);

        clientesRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/addCliente.png"))); // NOI18N
        clientesRelatorio.setText("Clientes");
        clientesRelatorio.setFocusable(false);
        clientesRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clientesRelatorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clientesRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesRelatorioActionPerformed(evt);
            }
        });
        barraCliente.add(clientesRelatorio);

        transacoesRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/transacoes2.png"))); // NOI18N
        transacoesRelatorio.setText("Transações");
        transacoesRelatorio.setFocusable(false);
        transacoesRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transacoesRelatorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        transacoesRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transacoesRelatorioActionPerformed(evt);
            }
        });
        barraCliente.add(transacoesRelatorio);

        produtosRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/glasses.png"))); // NOI18N
        produtosRelatorio.setText("Produtos");
        produtosRelatorio.setFocusable(false);
        produtosRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        produtosRelatorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraCliente.add(produtosRelatorio);

        notasDeVendaRelatório.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nota.png"))); // NOI18N
        notasDeVendaRelatório.setText("Nota de Venda");
        notasDeVendaRelatório.setFocusable(false);
        notasDeVendaRelatório.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        notasDeVendaRelatório.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraCliente.add(notasDeVendaRelatório);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 605, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clientesRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesRelatorioActionPerformed
        
    }//GEN-LAST:event_clientesRelatorioActionPerformed

    private void transacoesRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transacoesRelatorioActionPerformed
    
    }//GEN-LAST:event_transacoesRelatorioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraCliente;
    private javax.swing.JButton clientesRelatorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton notasDeVendaRelatório;
    private javax.swing.JButton produtosRelatorio;
    private javax.swing.JButton transacoesRelatorio;
    // End of variables declaration//GEN-END:variables
}
