/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controlador.ControladorCliente;
import controlador.ControladorCompra;
import controlador.ControladorProduto;
import controlador.ControladorTransacoes;
import java.sql.Date;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.Cliente;
import utils.Compra;
import utils.Produto;
import utils.Transacoes;

/**
 *
 * @author Igor
 */
public class PainelVendas extends javax.swing.JPanel {

    /**
     * Creates new form PainelVendas
     */
    private ArrayList<Cliente> clientes;
    private ArrayList<Produto> produtos;
    private ArrayList<Transacoes> transacoesDasCompras = new ArrayList<Transacoes>();
    DefaultTableModel modelClientes;
    DefaultTableModel modelProdutos;
    DefaultTableModel modelCompras;
    ControladorCliente controladorCliente = new ControladorCliente();
    ControladorProduto controladorProduto = new ControladorProduto();
    ControladorTransacoes controladorTransacoes = new ControladorTransacoes();
    ControladorCompra controladorCompra = new ControladorCompra();
    Cliente clienteSelecionado;
    Produto produtoSelecionado;
    DecimalFormat df = new DecimalFormat("#.##");

    public PainelVendas() {
        initComponents();

        //aba de clientes
        campoBuscaClienteCPF.setEnabled(false);
        campoBuscaClienteNome.setEnabled(false);
        abasVendas.setEnabledAt(1, false);
        abasVendas.setEnabledAt(2, false);

        //aba de produtos
        campoBuscaCodigo.setEnabled(false);
        campoBuscaNome.setEnabled(false);

        //aba de vendas
        campoCPFEscolhido.setEnabled(false);
        campoNomeEscolhido.setEnabled(false);
        nomeProdutoEscolhido.setEnabled(false);
        codigoProdutoEscolhido.setEnabled(false);
        campoPreco.setEnabled(false);
        campoValor.setEnabled(false);
        campoValorFinal.setEnabled(false);

        modelProdutos = (DefaultTableModel) tabelaProdutos.getModel();
        modelClientes = (DefaultTableModel) tabelaClientes.getModel();
        modelCompras = (DefaultTableModel) tabelaTransacoesCompra.getModel();

        //controle de botõe
        realizarVenda.setEnabled(false);
        selecionarProduto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraCliente = new javax.swing.JToolBar();
        selecionarCliente = new javax.swing.JButton();
        selecionarProduto = new javax.swing.JButton();
        realizarVenda = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        abasVendas = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoBuscaClienteCPF = new javax.swing.JTextField();
        checkCPF = new javax.swing.JCheckBox();
        checkNome = new javax.swing.JCheckBox();
        campoBuscaClienteNome = new javax.swing.JTextField();
        buscarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        cancelar = new javax.swing.JButton();
        selecionar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoBuscaCodigo = new javax.swing.JTextField();
        campoBuscaNome = new javax.swing.JTextField();
        buscarProduto = new javax.swing.JButton();
        checkNomeProduto = new javax.swing.JCheckBox();
        checkCodigoProduto = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        cancelarProduto = new javax.swing.JButton();
        selectProduto = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoNomeEscolhido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoCPFEscolhido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nomeProdutoEscolhido = new javax.swing.JTextField();
        codigoProdutoEscolhido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoQuantidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campoPreco = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoValor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        campoDesconto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        campoValorFinal = new javax.swing.JTextField();
        adicionarCarrinho = new javax.swing.JButton();
        realizaVenda = new javax.swing.JButton();
        selecionarMaisProdutos = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaTransacoesCompra = new javax.swing.JTable();
        removerProduto = new javax.swing.JButton();

        barraCliente.setOrientation(javax.swing.SwingConstants.VERTICAL);
        barraCliente.setRollover(true);

        selecionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/addCliente.png"))); // NOI18N
        selecionarCliente.setText("Selecione o cliente");
        selecionarCliente.setFocusable(false);
        selecionarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selecionarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        selecionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarClienteActionPerformed(evt);
            }
        });
        barraCliente.add(selecionarCliente);

        selecionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/glasses.png"))); // NOI18N
        selecionarProduto.setText("Selecione o produto");
        selecionarProduto.setFocusable(false);
        selecionarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selecionarProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        selecionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarProdutoActionPerformed(evt);
            }
        });
        barraCliente.add(selecionarProduto);

        realizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/transacoes2.png"))); // NOI18N
        realizarVenda.setText("Realize a venda");
        realizarVenda.setFocusable(false);
        realizarVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        realizarVenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        realizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarVendaActionPerformed(evt);
            }
        });
        barraCliente.add(realizarVenda);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Selecione o cliente");

        jLabel7.setText("Busque o cliente por CPF/CNPJ");

        checkCPF.setText("Busque por CPF/CNPJ");
        checkCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCPFActionPerformed(evt);
            }
        });

        checkNome.setText("Busque por nome");
        checkNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNomeActionPerformed(evt);
            }
        });

        buscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        buscarCliente.setText("Buscar");
        buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteActionPerformed(evt);
            }
        });

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF/CNPJ", "Nome", "Endereço", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(tabelaClientes);

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        selecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/select.png"))); // NOI18N
        selecionar.setText("Selecionar");
        selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(campoBuscaClienteCPF)
                                    .addComponent(campoBuscaClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkCPF)
                                    .addComponent(checkNome))
                                .addGap(0, 434, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(buscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selecionar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBuscaClienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkCPF))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBuscaClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarCliente)
                    .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selecionar))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        abasVendas.addTab("Selecione o cliente", jPanel2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Selecione o produto");

        jLabel8.setText("Busque o produto por código");

        buscarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        buscarProduto.setText("Buscar");
        buscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProdutoActionPerformed(evt);
            }
        });

        checkNomeProduto.setText("Busque pelo nome");
        checkNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNomeProdutoActionPerformed(evt);
            }
        });

        checkCodigoProduto.setText("Busque pelo código");
        checkCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCodigoProdutoActionPerformed(evt);
            }
        });

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Preço", "Quantidade", "Grupo"
            }
        ));
        jScrollPane2.setViewportView(tabelaProdutos);

        cancelarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        cancelarProduto.setText("Cancelar");
        cancelarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarProdutoActionPerformed(evt);
            }
        });

        selectProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/select.png"))); // NOI18N
        selectProduto.setText("Selecionar");
        selectProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(campoBuscaCodigo)
                                    .addComponent(campoBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkCodigoProduto)
                                    .addComponent(checkNomeProduto)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 462, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(buscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelarProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBuscaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkCodigoProduto))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkNomeProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarProduto)
                            .addComponent(cancelarProduto))
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(selectProduto))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        abasVendas.addTab("Selecione o produto", jPanel3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Realize a venda");

        jLabel4.setText("Nome do cliente");

        jLabel5.setText("CPF/CNPJ do cliente");

        jLabel6.setText("Nome do produto");

        jLabel9.setText("Código do produto");

        jLabel10.setText("Quantidade");

        jLabel11.setText("Preço por unidade");

        jLabel12.setText("Valor da transação");

        jLabel13.setText("Desconto dado:");

        campoDesconto.setText("0,00");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Valor Final da Transação");

        campoValorFinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        adicionarCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/carrinho.png"))); // NOI18N
        adicionarCarrinho.setText("Adiciona Produto");
        adicionarCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarCarrinhoActionPerformed(evt);
            }
        });

        realizaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/select.png"))); // NOI18N
        realizaVenda.setText("Confirma Venda");
        realizaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizaVendaActionPerformed(evt);
            }
        });

        selecionarMaisProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.png"))); // NOI18N
        selecionarMaisProdutos.setText("Selecionar mais produtos");
        selecionarMaisProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarMaisProdutosActionPerformed(evt);
            }
        });

        tabelaTransacoesCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "CPF/CNPJ", "Produto", "Código", "Quantidade", "Preço", "Valor", "Desconto", "Data"
            }
        ));
        jScrollPane3.setViewportView(tabelaTransacoesCompra);

        removerProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menos.png"))); // NOI18N
        removerProduto.setText("Remover Produto");
        removerProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(campoValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(adicionarCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removerProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selecionarMaisProdutos))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(campoNomeEscolhido, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                                    .addComponent(nomeProdutoEscolhido))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(campoCPFEscolhido, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                                    .addComponent(codigoProdutoEscolhido))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(campoDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(realizaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNomeEscolhido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeProdutoEscolhido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCPFEscolhido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoProdutoEscolhido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarCarrinho)
                    .addComponent(selecionarMaisProdutos)
                    .addComponent(removerProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(realizaVenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        abasVendas.addTab("Realize a venda", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abasVendas))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(barraCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(abasVendas)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selecionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarClienteActionPerformed
        abasVendas.setSelectedIndex(0);

        realizarVenda.setEnabled(false);
        selecionarCliente.setEnabled(true);
        selecionarProduto.setEnabled(false);

        abasVendas.setEnabledAt(0, true);
        abasVendas.setEnabledAt(1, false);
        abasVendas.setEnabledAt(2, false);
    }//GEN-LAST:event_selecionarClienteActionPerformed

    private void selecionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarProdutoActionPerformed
        abasVendas.setSelectedIndex(1);

        realizarVenda.setEnabled(false);
        selecionarCliente.setEnabled(false);
        selecionarProduto.setEnabled(true);

        abasVendas.setEnabledAt(0, false);
        abasVendas.setEnabledAt(1, true);
        abasVendas.setEnabledAt(2, false);
    }//GEN-LAST:event_selecionarProdutoActionPerformed

    private void realizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarVendaActionPerformed
        abasVendas.setSelectedIndex(2);

        realizarVenda.setEnabled(true);
        selecionarCliente.setEnabled(false);
        selecionarProduto.setEnabled(false);

        abasVendas.setEnabledAt(0, false);
        abasVendas.setEnabledAt(1, false);
        abasVendas.setEnabledAt(2, true);
    }//GEN-LAST:event_realizarVendaActionPerformed

    private void checkCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCPFActionPerformed
        if (checkCPF.isSelected()) {
            campoBuscaClienteCPF.setEnabled(true);
            checkNome.setSelected(false);
            campoBuscaClienteNome.setEnabled(false);
        } else {
            campoBuscaClienteCPF.setEnabled(false);
        }
    }//GEN-LAST:event_checkCPFActionPerformed

    private void checkNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNomeActionPerformed
        if (checkNome.isSelected()) {
            campoBuscaClienteNome.setEnabled(true);
            campoBuscaClienteCPF.setEnabled(false);
            checkCPF.setSelected(false);
        } else {
            campoBuscaClienteNome.setEnabled(false);
        }
    }//GEN-LAST:event_checkNomeActionPerformed

    private void buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteActionPerformed

        if (campoBuscaClienteNome.getText() != null && !campoBuscaClienteNome.getText().equals("") && campoBuscaClienteNome.isEnabled()) {
            clientes = controladorCliente.buscaClientesPorNome(campoBuscaClienteNome.getText());
        } else if (campoBuscaClienteCPF.getText() != null && !campoBuscaClienteCPF.getText().equals("") && campoBuscaClienteCPF.isEnabled()) {
            clientes = controladorCliente.buscaClientesPorCPFCNPJ(campoBuscaClienteCPF.getText());
        } else {
            clientes = controladorCliente.buscaTodosOsClientes();
        }

        modelClientes.setNumRows(0);

        for (int i = 0; i < clientes.size(); i++) {
            Vector vec = new Vector();
            vec.add(0, clientes.get(i).getCpf_cnpj());
            vec.add(1, clientes.get(i).getNome());
            vec.add(2, clientes.get(i).getEndereco());
            vec.add(3, clientes.get(i).getTelefone());
            modelClientes.addRow(vec);
        }

        this.repaint();
    }//GEN-LAST:event_buscarClienteActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        campoBuscaClienteCPF.setEnabled(false);
        campoBuscaClienteNome.setEnabled(false);
        checkCPF.setSelected(false);
        checkNome.setSelected(false);

        modelClientes.setNumRows(0);
    }//GEN-LAST:event_cancelarActionPerformed

    private void selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarActionPerformed
        try {
            int selecionado = tabelaClientes.getSelectedRow();
            clienteSelecionado = clientes.get(selecionado);
            JOptionPane.showMessageDialog(this, "Cliente selecionado com sucesso", "Warning", JOptionPane.WARNING_MESSAGE);
            abasVendas.setSelectedIndex(1);
            abasVendas.setEnabledAt(0, false);
            abasVendas.setEnabledAt(2, false);
            abasVendas.setEnabledAt(1, true);

            realizarVenda.setEnabled(false);
            selecionarCliente.setEnabled(false);
            selecionarProduto.setEnabled(true);

            campoCPFEscolhido.setText(clienteSelecionado.getCpf_cnpj());
            campoNomeEscolhido.setText(clienteSelecionado.getNome());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Um cliente deve ser selecionado na tabela", null, JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_selecionarActionPerformed

    private void buscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProdutoActionPerformed

        if (checkNomeProduto.isSelected()) {
            produtos = controladorProduto.buscaProdutosPorNome(campoBuscaNome.getText());
        } else if (checkCodigoProduto.isSelected()) {
            produtos = controladorProduto.buscaClientesPorCodigo(campoBuscaCodigo.getText());
        } else {
            produtos = controladorProduto.buscaTodosOsProdutos();
        }

        modelProdutos.setNumRows(0);

        for (int i = 0; i < produtos.size(); i++) {
            Vector vec = new Vector();
            vec.add(0, produtos.get(i).getCodigo());
            vec.add(1, produtos.get(i).getNome());
            vec.add(2, produtos.get(i).getPrecoPorUnidade());
            vec.add(3, produtos.get(i).getQuantidadeEstoque());
            vec.add(4, produtos.get(i).getTipoProduto());
            modelProdutos.addRow(vec);
        }

        this.repaint();
    }//GEN-LAST:event_buscarProdutoActionPerformed

    private void checkNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNomeProdutoActionPerformed
        if (checkNomeProduto.isSelected()) {
            campoBuscaNome.setEnabled(true);
            campoBuscaCodigo.setEnabled(false);
            checkCodigoProduto.setSelected(false);
        } else {
            campoBuscaNome.setEnabled(false);
        }
    }//GEN-LAST:event_checkNomeProdutoActionPerformed

    private void checkCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCodigoProdutoActionPerformed
        if (checkCodigoProduto.isSelected()) {
            campoBuscaCodigo.setEnabled(true);
            checkNomeProduto.setSelected(false);
            campoBuscaNome.setEnabled(false);
        } else {
            campoBuscaCodigo.setEnabled(false);
        }
    }//GEN-LAST:event_checkCodigoProdutoActionPerformed

    private void cancelarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarProdutoActionPerformed
        campoBuscaCodigo.setEnabled(false);
        campoBuscaNome.setEnabled(false);
        checkCodigoProduto.setSelected(false);
        checkNomeProduto.setSelected(false);

        modelProdutos.setNumRows(0);
    }//GEN-LAST:event_cancelarProdutoActionPerformed

    private void selectProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectProdutoActionPerformed
        try {
            int selecionado = tabelaProdutos.getSelectedRow();
            produtoSelecionado = produtos.get(selecionado);
            JOptionPane.showMessageDialog(this, "Produto selecionado com sucesso", "Warning", JOptionPane.WARNING_MESSAGE);
            abasVendas.setSelectedIndex(2);
            abasVendas.setEnabledAt(0, false);
            abasVendas.setEnabledAt(2, true);
            abasVendas.setEnabledAt(1, false);

            realizarVenda.setEnabled(true);
            selecionarCliente.setEnabled(false);
            selecionarProduto.setEnabled(false);

            codigoProdutoEscolhido.setText(produtoSelecionado.getCodigo());
            nomeProdutoEscolhido.setText(produtoSelecionado.getNome());
            campoPreco.setText(produtoSelecionado.getPrecoPorUnidade());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Um produto deve ser selecionado na tabela", null, JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_selectProdutoActionPerformed

    private void realizaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizaVendaActionPerformed

    }//GEN-LAST:event_realizaVendaActionPerformed

    private void adicionarCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarCarrinhoActionPerformed
        java.util.Calendar cal = java.util.Calendar.getInstance();
        java.util.Date utilDate = cal.getTime();

        try {
            if (produtoSelecionado != null && clienteSelecionado != null) {
                if (produtoSelecionado.getQuantidadeEstoque() >= Integer.parseInt(campoQuantidade.getText())) {
                    if (!campoDesconto.getText().equals("") && !campoQuantidade.getText().equals("")) {
                        double valor = Integer.parseInt(campoQuantidade.getText()) * Double.parseDouble(produtoSelecionado.getPrecoPorUnidade());
                        double valorFinal = 0;



                        modelCompras.setNumRows(0);
                        transacoesDasCompras.add(new Transacoes(clienteSelecionado.getNome(), clienteSelecionado.getCpf_cnpj(), produtoSelecionado.getNome(), produtoSelecionado.getCodigo(), Integer.parseInt(campoQuantidade.getText()), Double.parseDouble(produtoSelecionado.getPrecoPorUnidade()), valor, Double.parseDouble(campoDesconto.getText().replace(",", ".")), new Date(utilDate.getDate()), 0));

                        for (int i = 0; i < transacoesDasCompras.size(); i++) {
                            Vector vec = new Vector();
                            vec.add(0, transacoesDasCompras.get(i).getNomeDoCliente());
                            vec.add(1, transacoesDasCompras.get(i).getCpf_cnpjCliente());
                            vec.add(2, transacoesDasCompras.get(i).getNomeDoProduto());
                            vec.add(3, transacoesDasCompras.get(i).getCodigoDoProduto());
                            vec.add(4, transacoesDasCompras.get(i).getQuantidadeVendidade());
                            vec.add(5, df.format(transacoesDasCompras.get(i).getPrecoPorUnidade()));
                            vec.add(6, df.format(transacoesDasCompras.get(i).getValorTotalDaTransacao()));
                            vec.add(7, df.format(transacoesDasCompras.get(i).getDescontoDado()));
                            vec.add(8, transacoesDasCompras.get(i).getData());
                            modelCompras.addRow(vec);
                        }

                        for (int z = 0; z < transacoesDasCompras.size(); z++) {
                            valorFinal += transacoesDasCompras.get(z).getValorTotalDaTransacao() - transacoesDasCompras.get(z).getDescontoDado();
                        }


                        campoValor.setText(String.valueOf(df.format(valor)));
                        campoValorFinal.setText(String.valueOf(df.format(valorFinal)));
                        produtoSelecionado = null;

                        this.repaint();

                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Quantidade indisponível do produto", null, JOptionPane.OK_OPTION);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Transação não pôde ser realizada", null, JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_adicionarCarrinhoActionPerformed

    private void selecionarMaisProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarMaisProdutosActionPerformed
        abasVendas.setSelectedIndex(1);
        abasVendas.setEnabledAt(0, false);
        abasVendas.setEnabledAt(1, true);
        abasVendas.setEnabledAt(2, false);

        realizarVenda.setEnabled(false);
        selecionarCliente.setEnabled(false);
        selecionarProduto.setEnabled(true);

        this.campoQuantidade.setText("");
        this.campoDesconto.setText("0,00");
    }//GEN-LAST:event_selecionarMaisProdutosActionPerformed

    private void removerProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerProdutoActionPerformed
        if (tabelaTransacoesCompra.getSelectedRow() != -1) {
            transacoesDasCompras.remove(tabelaTransacoesCompra.getSelectedRow());

            modelCompras.setNumRows(0);
            for (int i = 0; i < transacoesDasCompras.size(); i++) {
                Vector vec = new Vector();
                vec.add(0, transacoesDasCompras.get(i).getNomeDoCliente());
                vec.add(1, transacoesDasCompras.get(i).getCpf_cnpjCliente());
                vec.add(2, transacoesDasCompras.get(i).getNomeDoProduto());
                vec.add(3, transacoesDasCompras.get(i).getCodigoDoProduto());
                vec.add(4, transacoesDasCompras.get(i).getQuantidadeVendidade());
                vec.add(5, df.format(transacoesDasCompras.get(i).getPrecoPorUnidade()));
                vec.add(6, df.format(transacoesDasCompras.get(i).getValorTotalDaTransacao()));
                vec.add(7, df.format(transacoesDasCompras.get(i).getDescontoDado()));
                vec.add(8, transacoesDasCompras.get(i).getData());
                modelCompras.addRow(vec);
            }
            
            double valorFinal = 0;
            for (int z = 0; z < transacoesDasCompras.size(); z++) {
                valorFinal += transacoesDasCompras.get(z).getValorTotalDaTransacao() - transacoesDasCompras.get(z).getDescontoDado();
            }
            campoValorFinal.setText(String.valueOf(df.format(valorFinal)));
                        

            this.repaint();
        } else {
            JOptionPane.showMessageDialog(this, "Deve-se selecionar um produto na tabela para remoção", null, JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_removerProdutoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abasVendas;
    private javax.swing.JButton adicionarCarrinho;
    private javax.swing.JToolBar barraCliente;
    private javax.swing.JButton buscarCliente;
    private javax.swing.JButton buscarProduto;
    private javax.swing.JTextField campoBuscaClienteCPF;
    private javax.swing.JTextField campoBuscaClienteNome;
    private javax.swing.JTextField campoBuscaCodigo;
    private javax.swing.JTextField campoBuscaNome;
    private javax.swing.JTextField campoCPFEscolhido;
    private javax.swing.JTextField campoDesconto;
    private javax.swing.JTextField campoNomeEscolhido;
    private javax.swing.JTextField campoPreco;
    private javax.swing.JTextField campoQuantidade;
    private javax.swing.JTextField campoValor;
    private javax.swing.JTextField campoValorFinal;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelarProduto;
    private javax.swing.JCheckBox checkCPF;
    private javax.swing.JCheckBox checkCodigoProduto;
    private javax.swing.JCheckBox checkNome;
    private javax.swing.JCheckBox checkNomeProduto;
    private javax.swing.JTextField codigoProdutoEscolhido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nomeProdutoEscolhido;
    private javax.swing.JButton realizaVenda;
    private javax.swing.JButton realizarVenda;
    private javax.swing.JButton removerProduto;
    private javax.swing.JButton selecionar;
    private javax.swing.JButton selecionarCliente;
    private javax.swing.JButton selecionarMaisProdutos;
    private javax.swing.JButton selecionarProduto;
    private javax.swing.JButton selectProduto;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTable tabelaTransacoesCompra;
    // End of variables declaration//GEN-END:variables
}
